/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "centaureaproj_com_centaurea_GameLibJNIWrapper.h"
#include <game.h>

JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv *env, jclass obj) {
    on_surface_created();
  }


JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv *env, jclass obj, jint width, jint height) {
    on_surface_changed();
  }

JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass) {
    on_draw_frame();
  }