/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "centaureaproj_com_centaurea_GameLibJNIWrapper.h"
#include <Game.h>
#include <GlGame.h>
#include "ITextureLoader.h"
#include "../textures/AndroidTextureLoader.h"

using namespace std;
using namespace Cenraurea::Common::GameEngine;

shared_ptr<Game> game;

JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv *env, jobject obj) {
    std::shared_ptr<ITextureLoader> textureLoader(new AndroidTextureLoader(env, obj));
    game = createGlGame(textureLoader);
    game->initialize();
  }


JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv *env, jobject obj, jint width, jint height) {
    game->screenSizeChanged(width, height);
  }

JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jobject obj) {
    game->update();
  }