/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class centaureaproj_com_centaurea_GameLibJNIWrapper */

#ifndef _Included_centaureaproj_com_centaurea_GameLibJNIWrapper
#define _Included_centaureaproj_com_centaurea_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     centaureaproj_com_centaurea_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     centaureaproj_com_centaurea_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     centaureaproj_com_centaurea_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_centaureaproj_com_centaurea_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
